package com.example.huanpet.model.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.huanpet.model.greendao.BuyersDao;
import com.example.huanpet.model.greendao.FosterDao;
import com.example.huanpet.model.greendao.UserDao;

import com.example.huanpet.model.bean.BuyersDaoDao;
import com.example.huanpet.model.bean.FosterDaoDao;
import com.example.huanpet.model.bean.UserDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig buyersDaoDaoConfig;
    private final DaoConfig fosterDaoDaoConfig;
    private final DaoConfig userDaoDaoConfig;

    private final BuyersDaoDao buyersDaoDao;
    private final FosterDaoDao fosterDaoDao;
    private final UserDaoDao userDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        buyersDaoDaoConfig = daoConfigMap.get(BuyersDaoDao.class).clone();
        buyersDaoDaoConfig.initIdentityScope(type);

        fosterDaoDaoConfig = daoConfigMap.get(FosterDaoDao.class).clone();
        fosterDaoDaoConfig.initIdentityScope(type);

        userDaoDaoConfig = daoConfigMap.get(UserDaoDao.class).clone();
        userDaoDaoConfig.initIdentityScope(type);

        buyersDaoDao = new BuyersDaoDao(buyersDaoDaoConfig, this);
        fosterDaoDao = new FosterDaoDao(fosterDaoDaoConfig, this);
        userDaoDao = new UserDaoDao(userDaoDaoConfig, this);

        registerDao(BuyersDao.class, buyersDaoDao);
        registerDao(FosterDao.class, fosterDaoDao);
        registerDao(UserDao.class, userDaoDao);
    }
    
    public void clear() {
        buyersDaoDaoConfig.clearIdentityScope();
        fosterDaoDaoConfig.clearIdentityScope();
        userDaoDaoConfig.clearIdentityScope();
    }

    public BuyersDaoDao getBuyersDaoDao() {
        return buyersDaoDao;
    }

    public FosterDaoDao getFosterDaoDao() {
        return fosterDaoDao;
    }

    public UserDaoDao getUserDaoDao() {
        return userDaoDao;
    }

}
